server:
    port: 8090

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/game?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 123456
    liquibase:
        change-log: db/changelog/db-changelog-root.xml